---
name: 'DNS Deployment'

on:
  push:
    branches:
      - main

jobs:
  preview:
    name: 'DNSControl Preview'
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install and configure GPG, Blackbox and dnscontrol
        shell: bash
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          sudo apt-get update -qq &&
          sudo apt-get -yqq install gnupg2
          git clone https://github.com/stackexchange/blackbox.git
          cd blackbox
          make manual-install
          cd ..
          gpg2 -v --import <(echo "$GPG_PRIVATE_KEY")
          GPG=gpg2 blackbox_postdeploy
          curl -Lo ./dnscontrol https://github.com/StackExchange/dnscontrol/releases/download/v3.11.0/dnscontrol-Linux
          chmod +x ./dnscontrol

      - name: Run dnscontrol preview
        shell: bash
        run: |
          ./dnscontrol preview

      - name: Run dnscontrol push
        shell: bash
        run: |
          ./dnscontrol push
